name: dist

on:
  release:
    types: [published]

jobs:

  generate:
    name: Generate static build by Hexo
    runs-on: ubuntu-latest
    steps:
    - name: node
      uses: actions/setup-node@v3
      with:
        node-version: '14'
    - name: checkout
      uses: actions/checkout@v3
    - name: build
      run: |
        npm install
        npm run build
    - name: upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: "dist-${{ github.event.release.tag_name }}"
        path: public

  nginx:
    name: Build and push image to serve static files by Nginx
    needs: generate
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: DockerHub login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: DockerHub metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: yipengh/blog
    - name: download artifacts
      uses: actions/download-artifact@v3
      with:
        name: "dist-${{ github.event.release.tag_name }}"
        path: public
    - name: Build and push image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: "yipengh/blog:${{ github.event.release.tag_name }}"
