name: dist

on:
  release:
    types: [published]

jobs:

  generate:
    name: Generate static build by Hexo
    runs-on: ubuntu-latest
    steps:
    - name: node
      uses: actions/setup-node@v4
      with:
        node-version: '14'
    - name: checkout
      uses: actions/checkout@v4
    - name: build
      run: |
        npm install
        npm run build
    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: "dist-${{ github.event.release.tag_name }}"
        path: public

  nginx:
    name: Build and push image to serve static files by Nginx
    needs: generate
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: download artifacts
      uses: actions/download-artifact@v4
      with:
        name: "dist-${{ github.event.release.tag_name }}"
        path: public
    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: "yipengh/blog:${{ github.event.release.tag_name }}"
    - name: Build and push image tagged latest
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: "yipengh/blog:latest"
